Add EntityHider (for Practice and MiniGames servers)
CobbleSword/NachoSpigot pull request #212
Opened 2021-10-29 11:42 UTC by SaithTime

Added an entity hider system if the shooter is not visible by other.

Method based on a private patched version of SpigotX

2021-10-29 22:44 UTC, Elierrr requested changes
Add a configuration option.

2021-10-30 03:22 UTC, CyberFlameGO requested changes
I agree with Elier, and it's easy to make this a configuration option

2021-10-30 03:22 UTC, CyberFlameGO commented on pom.xml
> +    <build>
Not everyone needs the API built, so in my opinion this is pretty pointless

2021-10-30 03:25 UTC, CyberFlameGO commented on pom.xml
> +    <build>
Nevermind iirc the server needs the api to build upon

2021-10-30 03:27 UTC, CyberFlameGO commented
You could also add `clean` (**NOT REPLACE**, so just make it `clean install` instead of just `install`) to the [server module](https://github.com/CobbleSword/NachoSpigot/blob/master/NachoSpigot-Server/pom.xml) default goals, and fix the [README.md](https://github.com/CobbleSword/NachoSpigot/blob/master/README.md) instructions. You may even be able to just add the default goals to the [parent POM](https://github.com/CobbleSword/NachoSpigot/blob/master/README.md) instead of messing around with each module

2021-11-01 13:18 UTC, Lucaskyy commented
Superseded by #213

2021-11-01 13:18 UTC, closed without merging