IonSpigot - Smooth & lag compensated potions
CobbleSword/NachoSpigot pull request #246
Opened 2021-11-15 14:57 UTC by Rastrian

- https://github.com/Samsuik/IonSpigot/blob/977187c2c4cbd96b0fbf589644a376b19d4f5930/TacoSpigot-Server-Patches/0025-Lag-Compensated-Potions.patch

2021-11-15 14:57 UTC, Lucaskyy commented
Did you close it by accident? :P

2021-11-15 17:19 UTC, Lucaskyy commented
@Rastrian Is this PR done?

2021-11-15 17:19 UTC, Lucaskyy approved these changes

2021-11-15 21:03 UTC, Elierrr requested changes

2021-11-15 21:03 UTC, Elierrr commented on NachoSpigot-Server/src/main/java/me/elier/nachospigot/config/NachoConfig.java
> +        c.addComment("settings.lag-compensated-potions", "Enables lag compesation throwing potions");
Bump config version

2021-11-16 00:58 UTC, Rastrian commented
> @Rastrian Is this PR done?

basically yeah, im maybe thinking in draft and do hit detection / knockback async

2021-11-16 04:04 UTC, CyberFlameGO commented
That doesn't sound like a good idea

2021-11-16 04:30 UTC, andreasdc commented
> > @Rastrian Is this PR done?

It will be the best to improve performance of ticking and movement of entities. Implementing Starlight would be nice too.

2021-11-16 04:57 UTC, Rastrian commented
> > > @Rastrian Is this PR done?
> 
> It will be the best to improve performance of ticking and movement of entities. Implementing Starlight would be nice too.

im literally working with async entity tracking now

2021-11-16 04:58 UTC, Rastrian commented
> That doesn't sound like a good idea

Agreed, maybe doing little PRs its better.

2021-11-16 04:58 UTC, andreasdc commented
> w

Waste of time

2021-11-16 04:59 UTC, Rastrian commented
> > w
> 
> Waste of time

ewwww, async entity tracking literally fix issues with entity movement.

2021-11-16 05:00 UTC, andreasdc commented
> > > w
> > 
> > 
> > Waste of time
> 
> ewwww, async entity tracking literally fix issues with entity movement.

Ok then waste some time and come back when you will get to my point of view :P

2021-11-16 05:02 UTC, Rastrian commented
> > > > w
> > > 
> > > 
> > > Waste of time
> > 
> > 
> > ewwww, async entity tracking literally fix issues with entity movement.
> 
> Ok then waste some time and come back when you will get to my point of view :P

what point of view dude? wtf are you talking about.

2021-11-16 05:03 UTC, andreasdc commented
> > w
> 
> Waste of time

this + you won't optimize movement by doing async tracker, it's better to focus on improving code of movement and ticking

2021-11-16 05:07 UTC, Rastrian commented
> > > w
> > 
> > 
> > Waste of time
> 
> this + you won't optimize movement by doing async tracker, it's better to focus on improving code of movement and ticking

an parallel entity tracking its literally optimizing the movement of entity.

IonSpigot implements the config faster-cannon-tracker, which improves a bit how entities work compared to the original implementation. But that doesn't totally solve the issue because this movement is intense when you put several entities simultaneously.

2021-11-16 05:08 UTC, Rastrian commented
> > > w
> > 
> > 
> > Waste of time
> 
> this + you won't optimize movement by doing async tracker, it's better to focus on improving code of movement and ticking
> 
> I'm far forward in such things.

If you're really ahead why don't you just raise a PR contributing this issue?

2021-11-16 05:11 UTC, andreasdc commented
> > > > w
> > > 
> > > 
> > > Waste of time
> > 
> > 
> > this + you won't optimize movement by doing async tracker, it's better to focus on improving code of movement and ticking
> 
> an parallel entity tracking its literally optimizing the movement of entity.
> 
> IonSpigot implements the config faster-cannon-tracker, which improves a bit how entities work compared to the original implementation. But that doesn't totally solve the issue because this movement is intense when you put several entities simultaneously.

Move, getCubes, t_ (tick), checkBlockCollisions, raytracing (double in interactions).

I do it privately at the moment, maybe I will share something other than advices and feedback sometime. 🚀

2021-11-16 09:02 UTC, Rastrian commented
Bump @Lucaskyy

2021-11-16 09:31 UTC, Lucaskyy commented
All good then, thank you for this PR! :)

2021-11-16 09:31 UTC, merged