Authentication implementation.
CobbleSword/NachoSpigot pull request #321
Opened 2022-01-08 23:15 UTC by sadcenter

# Description

Changes auth implementation from yggdrasil one to mine one. (toggleable in configuration)
It uses https://github.com/Electroid/mojang-api and caches the player's texture to the file.

Fixes/Adds #127 (Not completely due it's impossible, more info in `Additional comments` section.)

# How has this been tested?

Tested by generating skulls and toggling `online-mode`

# Additional Comments

It's impossible to remove the delay completely in async action (sync would be even worse). However, we can try to reduce the delay by using better API, cache, etc. 
Default cache time is 1 day.
If there's something wrong with changes, let me know.

# Checklist:

- [X] I have reviewed my code thoroughly.
- [X] I have tested my code. (I recommend testing it again, it's a big update so I might have skipped something)
- [X] My changes generate no new warnings

2022-01-08 23:50 UTC, Elierrr reviewed
Looks good! This is just a brief review, I'll do a full review and test when I can. Also you should try to not edit the formatting of the files, I see that there's a lot of files with just formatting changes.

2022-01-08 23:50 UTC, Elierrr commented on NachoSpigot-Server/src/main/java/me/elier/nachospigot/config/NachoConfig.java
> +        c.addComment("settings.use-nacho-authenticator", "Enables nacho authentication");
```suggestion
        c.addComment("settings.use-nacho-authenticator", "Enables our own authentication system which uses Electroid's Mojang API.");
```

2022-01-08 23:50 UTC, Elierrr commented on NachoSpigot-Server/src/main/java/net/minecraft/server/DedicatedServer.java
> +            this.setPlayerList(new DedicatedPlayerList(this));
```suggestion
            // Nacho start - Use our own authentication system
            YggdrasilAuthenticationService yggdrasilAuthenticationService = new YggdrasilAuthenticationService(super.e, UUID.randomUUID().toString());
            this.V = NachoConfig.useNachoAuthenticator ? new NachoAuthenticatorService(yggdrasilAuthenticationService) : yggdrasilAuthenticationService;
            this.W = this.V.createMinecraftSessionService();
            this.Y = this.V.createProfileRepository();
            // Nacho end

            this.setPlayerList(new DedicatedPlayerList(this));
```

2022-01-08 23:50 UTC, Elierrr commented on NachoSpigot-Server/src/main/java/net/minecraft/server/ItemSkull.java
> +            }
```suggestion
            // Nacho start - Use our own authentication system
            if(NachoConfig.useNachoAuthenticator) {
                ((NachoAuthenticatorService) MinecraftServer.getServer().getAuthenticator()).getProfile(gameprofile.getName()).thenAccept(profile -> {
                    nbttagcompound.set("SkullOwner", GameProfileSerializer.serialize(new NBTTagCompound(), profile));
                });
            } else {
                TileEntitySkull.b(gameprofile, new Predicate<GameProfile>() {
                    @Override
                    public boolean apply(@Nullable GameProfile gameProfile) {
                        nbttagcompound.set("SkullOwner", GameProfileSerializer.serialize(new NBTTagCompound(), gameProfile));
                        return false;
                    }
                });
            }
            // Nacho end
```

2022-01-08 23:50 UTC, Elierrr commented on NachoSpigot-Server/src/main/java/net/minecraft/server/MinecraftServer.java
> +        }
```suggestion
        // Nacho start
        if(NachoConfig.useNachoAuthenticator) {
            ((NachoAuthenticatorService) this.V).getProfileCache().setTicked(false);
        }
        // Nacho end
```

2022-01-08 23:50 UTC, Elierrr commented on NachoSpigot-Server/src/main/java/net/minecraft/server/MinecraftServer.java
> +    }
```suggestion
    // Nacho start
    public AuthenticationService getAuthenticator() {
        return this.V;
    }
    // Nacho end
```

2022-01-08 23:50 UTC, Elierrr commented on NachoSpigot-Server/src/main/java/net/minecraft/server/TileEntitySkull.java
> +        // Nacho start
```suggestion
        // Spigot start
```

2022-01-08 23:50 UTC, Elierrr commented on NachoSpigot-Server/src/main/java/net/minecraft/server/TileEntitySkull.java
>          setSkullType( 0 ); // Work around client bug
```suggestion
        setSkullType( 0 ); // Work around client bug
        // Nacho start - Use our own authentication system
```

2022-01-08 23:50 UTC, Elierrr commented on NachoSpigot-Server/src/main/java/net/minecraft/server/TileEntitySkull.java
> +        // Nacho end
```suggestion
        // Spigot/Nacho end
```

2022-01-08 23:50 UTC, Elierrr commented on NachoSpigot-Server/src/main/java/org/bukkit/craftbukkit/inventory/CraftMetaSkull.java
> +                setSkullNbt(tag, gameProfile);
```suggestion
            // Nacho start - Use our own authentication system
            setSkullNbt(tag, profile);

            if (NachoConfig.useNachoAuthenticator) {
                NachoAuthenticatorService authenticator = (NachoAuthenticatorService) MinecraftServer.getServer().getAuthenticator();

                authenticator.getProfile(profile.getName()).thenAccept(gameProfile -> {
                    setSkullNbt(tag, gameProfile);
                });
            } else TileEntitySkull.b(profile, gameProfile -> { // Spigot - do an async lookup of the profile
                setSkullNbt(tag, gameProfile);
                // Nacho end
```

2022-01-08 23:50 UTC, Elierrr commented on NachoSpigot-Server/src/main/java/org/bukkit/craftbukkit/inventory/CraftMetaSkull.java
> +    }
```suggestion
    // Nacho start
    private void setSkullNbt(NBTTagCompound tag, GameProfile gameProfile) {
        NBTTagCompound ownerTag = new NBTTagCompound();
        GameProfileSerializer.serialize(ownerTag, gameProfile);
        tag.set(SKULL_OWNER.NBT, ownerTag);
    }
    // Nacho end
```

2022-01-08 23:50 UTC, Elierrr commented on NachoSpigot-Server/src/main/java/org/bukkit/craftbukkit/inventory/CraftMetaSkull.java
> +                    TileEntitySkull.skinCache.getIfPresent(name);
```suggestion
                // Nacho start - Use our own authentication system
        	profile = NachoConfig.useNachoAuthenticator ?
                    ((NachoAuthenticatorService) MinecraftServer.getServer().getAuthenticator()).getPresentProfile(name.toLowerCase(java.util.Locale.ROOT)) :
                    TileEntitySkull.skinCache.getIfPresent(name.toLowerCase(java.util.Locale.ROOT)); // Paper // tries to get from skincache
                // Nacho end
```

2022-01-10 17:43 UTC, xzolw approved these changes

2022-01-10 18:43 UTC, Blyrex commented
its not a good idea to use private apis in this project

2022-01-16 21:50 UTC, Elierrr requested changes

2022-01-16 21:50 UTC, Elierrr commented on NachoSpigot-Server/src/main/java/com/github/sadcenter/auth/NachoAuthenticatorService.java
> +public class NachoAuthenticatorService implements AuthenticationService {
This class should be called `NachoAuthenticationService`

2022-01-16 21:50 UTC, Elierrr commented on NachoSpigot-Server/src/main/java/com/github/sadcenter/auth/storage/ProfileCache.java
> +                e.printStackTrace();
```suggestion
                Bukkit.getLogger().log(Level.SERVERE, "Error while creating texturecache.json", e);
```

2022-01-16 21:50 UTC, Elierrr commented on NachoSpigot-Server/src/main/java/com/github/sadcenter/auth/storage/ProfileCache.java
> +import java.util.concurrent.Executors;
```suggestion
import java.util.concurrent.Executors;
import java.util.logging.Level;
```

2022-01-16 21:50 UTC, Elierrr commented on NachoSpigot-Server/src/main/java/com/github/sadcenter/auth/storage/ProfileCache.java
> +import org.apache.commons.io.FileUtils;
```suggestion
import org.apache.commons.io.FileUtils;
import org.bukkit.Bukkit;
```

2022-01-16 21:50 UTC, Elierrr commented on NachoSpigot-Server/src/main/java/com/github/sadcenter/auth/storage/ProfileCache.java
> +            e.printStackTrace();
```suggestion
            Bukkit.getLogger().log(Level.SERVERE, "Error while loading profile caches", e);
```

2022-01-16 21:50 UTC, Elierrr commented on NachoSpigot-Server/src/main/java/com/github/sadcenter/auth/session/NachoSessionService.java
> +import com.mojang.authlib.properties.PropertyMap;
```suggestion
import com.mojang.authlib.properties.PropertyMap;
import org.bukkit.Bukkit;
```

2022-01-16 21:50 UTC, Elierrr commented on NachoSpigot-Server/src/main/java/com/github/sadcenter/auth/session/NachoSessionService.java
> +            e.printStackTrace();
```suggestion
            Bukkit.getLogger().log(Level.SERVERE, "Error loading profile " + gameProfile.getName() + " (UUID: " + gameProfile.getId() + ")", e);
```

2022-01-18 11:52 UTC, Elierrr approved these changes

2022-01-18 11:53 UTC, sadcenter commented
> its not a good idea to use private apis in this project

I personally trust this API. I haven't ever met with a situation when this API is down (I'm using this in every project that needs data from Mojang). But not everyone has to trust it, that's why I added an option in the configuration to disable that.
IMO it would be great to add an option that allows you to toggle between ashcon API and Mojang's API

2022-01-19 05:25 UTC, Ytnoos commented
> > its not a good idea to use private apis in this project
> 
> 
> 
> I personally trust this API. I haven't ever met with a situation when this API is down (I'm using this in every project that needs data from Mojang). But not everyone has to trust it, that's why I added an option in the configuration to disable that.
> 
> IMO it would be great to add an option that allows you to toggle between ashcon API and Mojang's API

I think it would be good to automatically switch to Mojang's API if any exception is caught with ashcon API

2022-01-19 11:21 UTC, LewUwU approved these changes

2022-01-19 11:26 UTC, CyberFlameGO commented
> its not a good idea to use private apis in this project

The API seems open source (as declared on the issue init message) and claims to be hosted on Cloudflare Workers

2022-01-19 11:28 UTC, CyberFlameGO commented
Oh also the person running and maintaining the API works at Cloudflare

2022-01-19 22:05 UTC, Elierrr requested changes

2022-01-19 22:05 UTC, Elierrr commented on NachoSpigot-Server/src/main/java/com/github/sadcenter/auth/NachoAuthenticationService.java
> +    public CompletableFuture<UUID> getUuid(String name) {
Should be `getUuidFromApi`

2022-01-19 22:05 UTC, Elierrr commented on NachoSpigot-Server/src/main/java/me/elier/nachospigot/config/NachoConfig.java
> +    }
```suggestion
    public static boolean useNachoAuthenticator;
    public static boolean alwaysUseMojang;

    private static void authentication() {
        useNachoAuthenticator = getBoolean("settings.authentication.use-nacho-authenticator", false);
        alwaysUseMojang = getBoolean("settings.authentication.always-use-mojang", true);
    }
```

2022-01-19 22:05 UTC, Elierrr commented on NachoSpigot-Server/src/main/java/me/elier/nachospigot/config/NachoConfig.java
> +        c.addComment("settings.authenticator.always-use-mojang", "Force to use mojang api no matter what");
```suggestion
        c.addComment("settings.authenticator.use-nacho-authentication", "Enables our own authentication system.");
        c.addComment("settings.authenticator.always-use-mojang", "Force to use mojang api no matter what");
```

2022-01-19 22:05 UTC, Elierrr commented on NachoSpigot-Server/src/main/java/me/elier/nachospigot/config/NachoConfig.java
> +        alwaysUseMojang = getBoolean("settings.authenticator.always-use-mojang", true);
Imo this should be inverted and be use-ashcon-api

2022-01-19 23:00 UTC, Lucaskyy commented
Looks good! Awesome PR :)
Since some reviews are not yet resolved, I'll wait until this is fully ready. Since I do not look at this repo often because I don't have much time, please ping me if possible so I can merge it :)

2022-01-19 23:09 UTC, Lucaskyy commented
Also, since I merged some PRs please fix the conflicts if possible :)

2022-01-20 00:25 UTC, sadcenter commented
oops Intelij IDEA kinda messed up I believe

2022-01-20 00:29 UTC, Elierrr commented
> oops Intelij IDEA kinda messed up I believe

Rebasing on master should fix it

2022-02-15 00:04 UTC, Lucaskyy commented
Is this PR stale or not?

2022-02-20 16:19 UTC, HowardZHY commented
is [https://github.com/CobbleSword/NachoSpigot/issues/353](https://github.com/CobbleSword/NachoSpigot/issues/353) related to this?

2022-02-20 21:03 UTC, sadcenter commented
> is #353 related to this?
it **might** fix it, but it's unlikely possible since authlib wasn't touched in nacho

2022-02-20 21:05 UTC, sadcenter commented
> Is this PR stale or not?

yea, I will resolve the conflicts tomorrow (if tram won't hit me or smth)

2022-02-23 10:34 UTC, sadcenter commented
CodeQL uses Java 11 where `exceptionallyCompose` and `exceptionallyComposeAsync` doesn't exist :/

2022-06-04 13:31 UTC, closed without merging