Disable Nether Roof Interaction
CobbleSword/NachoSpigot pull request #385
Opened 2022-03-24 20:39 UTC by crafter23456

I cant break the roof in creative or like that, seems robust, but i can place but not break on top of it and the message appears, yeah because its coded like it should do that. cause of my other PRs, the readme order will change anyways so i pasted it just on the bottom of the flamepaper patches

# Checklist:

- [x] I have reviewed my code thoroughly.
- [x] I have tested my code.
- [x] My changes generate no new warnings

2022-03-24 21:19 UTC, Elierrr requested changes

2022-03-24 21:19 UTC, Elierrr commented on NachoSpigot-Server/src/main/java/me/elier/nachospigot/config/NachoConfig.java
> +    public static boolean disableNetherroofDestroying;
Incorrect name, the config disabled placing on nether roof not destroying it

2022-03-24 21:19 UTC, Elierrr commented on NachoSpigot-Server/src/main/java/me/elier/nachospigot/config/NachoConfig.java
> +        c.addComment("settings.disable-nether-roof-destroying", "Disables destorying the nether roof.");
Update comment

2022-03-24 21:21 UTC, Elierrr commented
I don’t really see the point of this since it can very easily be done with a plugin

2022-03-25 20:05 UTC, Elierrr requested changes

2022-03-25 20:05 UTC, Elierrr commented on NachoSpigot-Server/src/main/java/me/elier/nachospigot/config/NachoConfig.java
> +    public static boolean enableNetherroofDestroying;
It should be `disableNetherroofInteraction`

2022-03-25 20:14 UTC, Elierrr approved these changes
This PR can be merged, however I don’t believe this is necessary since it can easily be done with a plugin

2022-03-29 16:06 UTC, Lucaskyy commented
I agree with Elier, plugins should handle this. NachoSpigot is for performance, not features plugins already do. Thanks anyway though!

2022-03-29 16:06 UTC, closed without merging